litellm_settings:
  vertex_project: "redislabs-sa-training-services" # Your Project ID
  vertex_location: "us-east1" # proj location

model_list:
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini-2.0-flash-lite
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-0125
    litellm_params:
      model: openai/gpt-3.5-turbo-0125
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-16k
    litellm_params:
      model: openai/gpt-3.5-turbo-16k
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini 
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY
  
